### ISSUE TITLE
Support defining constants in Scenario yaml file

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#28]
Proposed syntax:

```yaml
Scenario:
  consts:
     - foo: bar
     - password: d$32d7)sd
```
