### ISSUE TITLE
Cannot verify an integer value

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#32]
Give the scenario file defined:

```yaml
    - description: retrieve client quotes
      request:
        method: GET
        url: /api/v1/clients/27066/quotes
      response:
        json:
          size:
            - gt: 0
          0:
            clientId: 27066
```

Where `clientId` is an integer, however the Yaml file take the value `27066` as a String, thus the verification failed.
