### ISSUE TITLE
`scenario.yml` file: support declare and assign variable for a scenario

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#37]
Proposed syntax

```yaml
Scenario(X):
    variables:
        - foo: bar
        - anyName: ${func:randomStr}
```
