### ISSUE TITLE
`scenario.yml` - support expressions in scenario constants declaration

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#38]
Proposed syntax:

```yaml
Scenario(X):
    variables:
        - foo: bar
        - fooBar: ${foo} and bar
        - anyName: ${func:randomStr}
```
