### ISSUE TITLE
Support testing objects in unorderred list

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#4]
If the backend returns list of objects without predictable order, then we can't use the index to get them. Proposed solution:

```yaml
Scenario(Country service):
  fixtures:
    - test-data.yml
  descriptions: A service returns list of countries (in any order)
  interactions:
    - description: send request to the service
      request:
        method: GET
        url: /countries
      response:
        json:
          size: 2
          ?:
            name: China
          ?.name: France
```
