### ISSUE TITLE
Support file upload test

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#42]
Proposed request spec definition:

```yaml
request:
  url: /upload
  method: post
  type: multipart/form-data
  parts:
    - file1: file1.jpg
```

Where `file1.jpg` shall be put under `resources/e2e/upload` dir
