### ISSUE TITLE
Make it possible to do evaluation for response verification

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#43]
We already can refer to constants/cache/last result in the request spec, this is to extends the flexibility to response spec so that we can use constants/cache/last variables to verify the response.

For example,

```yaml
Scenario(CLIENT):
  constants:
    newClientName: ${func:randFullName}
  depends:
    - LOGIN
  interactions:
    - description: Create new Client
      request:
        method: POST
        url: /api/v1/clients
        json:
          clientName: ${newClientName}
      response:
        json:
          id:
            - exists: true
      cache:
        newClientId: id
    - description: retrieve the client been created
      request:
        accept: json
        method: GET
        url: /api/v1/clients/${newClientId}
      response:
        json:
          clientName: ${newClientName}
```

In the above scenario, we declared a constant `newClientName`, and we reference it in the request spec, which is supported already, and then we refer `newClientName` again in the response spec to check if the returned data matches what we have sent out
