### ISSUE TITLE
Support embedded reference in function

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#44]
Sample code:

```yaml
Scenario(CLIENT):
  constants:
    newClientName: ${func:randFullName}
    newClientShortName: ${func:subStr("${newClientName}", 0, 16)}
```

In the above sample, we have declared constant `newClientName` using function `randFullName` and then we refer to the `newClientName` in the subsequent `newClientShortName` declaration:

```yaml
newClientShortName: ${func:subStr("${newClientName}", 0, 16)}
```
