### ISSUE TITLE
Make function a universal reference point

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#48]
Right now function is only used to declare a constant. The request is to make it be referred in any place and can be used embedded in the middle of another expression, e.g.

```yaml
request:
    method: GET
    url: /foo/bar/${randStr()}
```
