### ISSUE TITLE
Support verifying html response

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#5]
For given response like

```html
<!DOCTYPE html>
<html lang="en-AU">
<head>
<meta charset="UTF-8">
<title>Hello World!</title>
</head>
<body>
<h1>Hello World!</h1>
</body>
</html>
```

Proposed testing scripts:

```yaml
Scenario(Hello World):
  description: a web page says Hello
  interactions:
    - description: send request to the app without parameter
      request:
        method: GET
        url: /
      response:
        html:
          h1: Hello World
          head title:
            - contains: Hello World
            - contains: ActFramework
```

Note how we use the css query to define the element to be verified, in the above case, they are

* `h1` - find the `<h1>` elements and get the first element to verify
* `head title` - find the `<head><title>` elements and get the first element to verify
