### ISSUE TITLE
Simplify RequestSpec declaration in scenario yaml file

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-e2e#51]
At the moment we declare `ResquestSpec` as:

```yaml
request:
    method: GET|POST|PUT|DELETE
    url: <url>
```

The simplified form will be

```yaml
request:
    get|post|put|delete: <url>
```
